@server=http://localhost:4004
@username=alice
@password=


### Employess
# @name Employess_GET
GET {{server}}/odata/v4/employee/Employess
Authorization: Basic {{username}}:{{password}}


### Employess
# @name Employess_POST
POST {{server}}/odata/v4/employee/Employess
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
 
  "employeeName": "Shiva",
  "email": "shiva@gmail.com",
  "salary": 11487.8
  
}


### Employess
# @name Employess_PATCH
PATCH {{server}}/odata/v4/employee/Employess('51a9c157-0480-446a-bf51-d3c1868cc60b')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
 
    "salary": 4870566.8
  
}


### Employess
# @name Employess_DELETE
DELETE {{server}}/odata/v4/employee/Employess(3b74ecdf-5e25-4bf4-848d-d3c7210585b3)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### approveEmployee
# @name approveEmployee_POST
POST {{server}}/odata/v4/employee/approveEmployee
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15578149-610c-4985-8f88-1b8fbc1a81d4"
}
